package agesgame;

import java.awt.Color;
import javax.swing.JLabel;

public class BuildingMenuImpl extends javax.swing.JPanel {
    private GameDataClass game;
    private CityViewImpl upperView;
            
    public BuildingMenuImpl(GameDataClass game,CityViewImpl cityView) {
        this.game = game;
        upperView = cityView;
        initComponents();
        scaleView();
        generateDisplay();
    }
    public void generateDisplay(){
        for (int i = 0; i < game.tables.getBuildMenuList().size(); i++){
            int box =  Integer.parseInt(game.tables.getBuildMenuList().get(i));
            getBuildingLabel(i).setVisible(true);
            getBuildingLabel(i).setText(game.tables.getBuildingName(box));
            
            if ( !game.hasResearched(game.tables.getBuildingTech(box)) && game.tables.getBuildingTech(box) > 0){
            	getBuildingLabel(i).setBackground(new java.awt.Color(100, 100, 100));
            }else{
            	getBuildingLabel(i).setBackground(new java.awt.Color(255, 255, 204));
            }
        }
        
        for (int i = game.tables.getBuildMenuList().size(); i < 16; i++){
        	getBuildingLabel(i).setVisible(false);
        }
        
        CostLabel.setVisible(false);
        SelectionLabel.setVisible(false);
    }
        
    public void setObjectBuy(int boxID) {
    	int ID = Integer.parseInt(game.tables.getBuildMenuList().get(boxID));
    	if (game.hasResearched(game.tables.getBuildingTech(ID)) || game.tables.getBuildingTech(ID) < 1){
    		generateDisplay();
    		getBuildingLabel(boxID).setBackground(new Color(255, 255, 100));
    		
    		SelectionLabel.setVisible(true);
    		SelectionLabel.setText(game.tables.getBuildingName(ID));
    		CostLabel.setVisible(true);
            CostLabel.setText(game.tables.getBuildingCostText(ID));
    		upperView.setBuildMode(ID);
    	}
    }
    public void close(){
        this.hide();
    }
    
    public JLabel getBuildingLabel(int i) {
        if (i == 0) {
            return BuildingLabel0;
        }if (i == 1) {
            return BuildingLabel1;
        }if (i == 2) {
            return BuildingLabel2;
        }if (i == 3) {
            return BuildingLabel3;
        }if (i == 4) {
            return BuildingLabel4;
        }if (i == 5) {
            return BuildingLabel5;
        }if (i == 6) {
            return BuildingLabel6;
        }if (i == 7) {
            return BuildingLabel7;
        }if (i == 8) {
            return BuildingLabel8;
        }if (i == 9) {
            return BuildingLabel9;
        }if (i == 10) {
            return BuildingLabel10;
        }if (i == 11) {
            return BuildingLabel11;
        }if (i == 12) {
            return BuildingLabel12;
        }if (i == 13) {
            return BuildingLabel13;
        }if (i == 14) {
            return BuildingLabel14;
        }if (i == 15) {
            return BuildingLabel15;
        }
        
        return null;
    }

    public void scaleView(){
    	for (int i = 0; i < 18; i ++){
        	JLabel setLabel = new javax.swing.JLabel();;
        	if (i == 0)
        		setLabel = BuildingLabel0;
        	if (i == 1)
        		setLabel = BuildingLabel1;
        	if (i == 2)
        		setLabel = BuildingLabel2;
        	if (i == 3)
        		setLabel = BuildingLabel3;
        	if (i == 4)
        		setLabel = BuildingLabel4;
        	if (i == 5)
				setLabel = BuildingLabel5;
			if (i == 6)
				setLabel = BuildingLabel6;
			if (i == 7)
				setLabel = BuildingLabel7;
			if (i == 8)
				setLabel = BuildingLabel8;
			if (i == 9)
				setLabel = BuildingLabel9; 
			if (i == 10)
        		setLabel = BuildingLabel10;
			if (i == 11)
        		setLabel = BuildingLabel11;
			if (i == 12)
        		setLabel = BuildingLabel12;
			if (i == 13)
        		setLabel = BuildingLabel13;
			if (i == 14)
        		setLabel = BuildingLabel14;
			if (i == 15)
        		setLabel = BuildingLabel15;
			if (i == 16)
        		setLabel = CostLabel;
			if (i == 17)
        		setLabel = SelectionLabel;
			
        	setLabel.setBounds(upperView.Scale(setLabel.getX()), upperView.Scale(setLabel.getY()), upperView.Scale(setLabel.getWidth()), upperView.Scale(setLabel.getHeight()));
        	setLabel.setFont(new java.awt.Font("Tahoma", 0, upperView.Scale(11))); // NOI18N

        }
    	SelectionLabel.setFont(new java.awt.Font("Tahoma", 0, upperView.Scale(14))); // NOI18N
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BuildingLabel0 = new javax.swing.JLabel();
        BuildingLabel1 = new javax.swing.JLabel();
        BuildingLabel2 = new javax.swing.JLabel();
        BuildingLabel3 = new javax.swing.JLabel();
        BuildingLabel4 = new javax.swing.JLabel();
        BuildingLabel5 = new javax.swing.JLabel();
        BuildingLabel6 = new javax.swing.JLabel();
        BuildingLabel7 = new javax.swing.JLabel();
        BuildingLabel8 = new javax.swing.JLabel();
        BuildingLabel9 = new javax.swing.JLabel();
        BuildingLabel10 = new javax.swing.JLabel();
        BuildingLabel11 = new javax.swing.JLabel();
        BuildingLabel12 = new javax.swing.JLabel();
        BuildingLabel13 = new javax.swing.JLabel();
        BuildingLabel14 = new javax.swing.JLabel();
        SelectionLabel = new javax.swing.JLabel();
        CostLabel = new javax.swing.JLabel();
        BuildingLabel15 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(null);

        BuildingLabel0.setBackground(new java.awt.Color(255, 255, 204));
        BuildingLabel0.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        BuildingLabel0.setText("BUILDING");
        BuildingLabel0.setOpaque(true);
        BuildingLabel0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuildingLabel0MouseClicked(evt);
            }
        });
        add(BuildingLabel0);
        BuildingLabel0.setBounds(11, 12, 57, 41);

        BuildingLabel1.setBackground(new java.awt.Color(255, 255, 204));
        BuildingLabel1.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        BuildingLabel1.setText("BUILDING");
        BuildingLabel1.setOpaque(true);
        BuildingLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuildingLabel1MouseClicked(evt);
            }
        });
        add(BuildingLabel1);
        BuildingLabel1.setBounds(78, 12, 57, 41);

        BuildingLabel2.setBackground(new java.awt.Color(255, 255, 204));
        BuildingLabel2.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        BuildingLabel2.setText("BUILDING");
        BuildingLabel2.setOpaque(true);
        BuildingLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuildingLabel2MouseClicked(evt);
            }
        });
        add(BuildingLabel2);
        BuildingLabel2.setBounds(150, 10, 55, 41);

        BuildingLabel3.setBackground(new java.awt.Color(255, 255, 204));
        BuildingLabel3.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        BuildingLabel3.setText("BUILDING");
        BuildingLabel3.setOpaque(true);
        BuildingLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuildingLabel3MouseClicked(evt);
            }
        });
        add(BuildingLabel3);
        BuildingLabel3.setBounds(220, 10, 57, 41);

        BuildingLabel4.setBackground(new java.awt.Color(255, 255, 204));
        BuildingLabel4.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        BuildingLabel4.setText("BUILDING");
        BuildingLabel4.setOpaque(true);
        BuildingLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuildingLabel4MouseClicked(evt);
            }
        });
        add(BuildingLabel4);
        BuildingLabel4.setBounds(10, 60, 57, 41);

        BuildingLabel5.setBackground(new java.awt.Color(255, 255, 204));
        BuildingLabel5.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        BuildingLabel5.setText("BUILDING");
        BuildingLabel5.setOpaque(true);
        BuildingLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuildingLabel5MouseClicked(evt);
            }
        });
        add(BuildingLabel5);
        BuildingLabel5.setBounds(80, 60, 55, 41);

        BuildingLabel6.setBackground(new java.awt.Color(255, 255, 204));
        BuildingLabel6.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        BuildingLabel6.setText("BUILDING");
        BuildingLabel6.setOpaque(true);
        BuildingLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuildingLabel6MouseClicked(evt);
            }
        });
        add(BuildingLabel6);
        BuildingLabel6.setBounds(150, 60, 57, 41);

        BuildingLabel7.setBackground(new java.awt.Color(255, 255, 204));
        BuildingLabel7.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        BuildingLabel7.setText("BUILDING");
        BuildingLabel7.setOpaque(true);
        BuildingLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuildingLabel7MouseClicked(evt);
            }
        });
        add(BuildingLabel7);
        BuildingLabel7.setBounds(220, 60, 57, 41);

        BuildingLabel8.setBackground(new java.awt.Color(255, 255, 204));
        BuildingLabel8.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        BuildingLabel8.setText("BUILDING");
        BuildingLabel8.setOpaque(true);
        BuildingLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuildingLabel8MouseClicked(evt);
            }
        });
        add(BuildingLabel8);
        BuildingLabel8.setBounds(10, 110, 55, 41);

        BuildingLabel9.setBackground(new java.awt.Color(255, 255, 204));
        BuildingLabel9.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        BuildingLabel9.setText("BUILDING");
        BuildingLabel9.setOpaque(true);
        BuildingLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuildingLabel9MouseClicked(evt);
            }
        });
        add(BuildingLabel9);
        BuildingLabel9.setBounds(80, 110, 57, 41);

        BuildingLabel10.setBackground(new java.awt.Color(255, 255, 204));
        BuildingLabel10.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        BuildingLabel10.setText("BUILDING");
        BuildingLabel10.setOpaque(true);
        BuildingLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuildingLabel10MouseClicked(evt);
            }
        });
        add(BuildingLabel10);
        BuildingLabel10.setBounds(150, 110, 57, 41);

        BuildingLabel11.setBackground(new java.awt.Color(255, 255, 204));
        BuildingLabel11.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        BuildingLabel11.setText("BUILDING");
        BuildingLabel11.setOpaque(true);
        BuildingLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuildingLabel11MouseClicked(evt);
            }
        });
        add(BuildingLabel11);
        BuildingLabel11.setBounds(220, 110, 55, 41);

        BuildingLabel12.setBackground(new java.awt.Color(255, 255, 204));
        BuildingLabel12.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        BuildingLabel12.setText("BUILDING");
        BuildingLabel12.setOpaque(true);
        BuildingLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuildingLabel12MouseClicked(evt);
            }
        });
        add(BuildingLabel12);
        BuildingLabel12.setBounds(10, 160, 57, 41);

        BuildingLabel13.setBackground(new java.awt.Color(255, 255, 204));
        BuildingLabel13.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        BuildingLabel13.setText("BUILDING");
        BuildingLabel13.setOpaque(true);
        BuildingLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuildingLabel13MouseClicked(evt);
            }
        });
        add(BuildingLabel13);
        BuildingLabel13.setBounds(80, 160, 57, 41);

        BuildingLabel14.setBackground(new java.awt.Color(255, 255, 204));
        BuildingLabel14.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        BuildingLabel14.setText("BUILDING");
        BuildingLabel14.setOpaque(true);
        BuildingLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuildingLabel14MouseClicked(evt);
            }
        });
        add(BuildingLabel14);
        BuildingLabel14.setBounds(150, 160, 55, 41);

        SelectionLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SelectionLabel.setText("SELECTION");
        add(SelectionLabel);
        SelectionLabel.setBounds(90, 300, 160, 22);

        CostLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CostLabel.setText("COST");
        add(CostLabel);
        CostLabel.setBounds(90, 330, 170, 17);

        BuildingLabel15.setBackground(new java.awt.Color(255, 255, 204));
        BuildingLabel15.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        BuildingLabel15.setText("BUILDING");
        BuildingLabel15.setOpaque(true);
        BuildingLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuildingLabel15MouseClicked(evt);
            }
        });
        add(BuildingLabel15);
        BuildingLabel15.setBounds(220, 160, 55, 41);
    }// </editor-fold>//GEN-END:initComponents

    private void BuildingLabel0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuildingLabel0MouseClicked
        setObjectBuy(0);
    }//GEN-LAST:event_BuildingLabel0MouseClicked

    private void BuildingLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuildingLabel1MouseClicked
        setObjectBuy(1);
    }//GEN-LAST:event_BuildingLabel1MouseClicked

    private void BuildingLabel2MouseClicked(java.awt.event.MouseEvent evt) {                                            
        setObjectBuy(2);
    }                                           

    private void BuildingLabel3MouseClicked(java.awt.event.MouseEvent evt) {                                            
        setObjectBuy(3);
    }                                           
    
    private void BuildingLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuildingLabel2MouseClicked
        setObjectBuy(4);
    }//GEN-LAST:event_BuildingLabel2MouseClicked

    private void BuildingLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuildingLabel5MouseClicked
        setObjectBuy(5);
    }//GEN-LAST:event_BuildingLabel5MouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void BuildingLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuildingLabel6MouseClicked
        setObjectBuy(6);
    }//GEN-LAST:event_BuildingLabel6MouseClicked

    private void BuildingLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuildingLabel7MouseClicked
    	setObjectBuy(7);
    }//GEN-LAST:event_BuildingLabel7MouseClicked

    private void BuildingLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuildingLabel8MouseClicked
    	setObjectBuy(8);
    }//GEN-LAST:event_BuildingLabel8MouseClicked

    private void BuildingLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuildingLabel9MouseClicked
    	setObjectBuy(9);
    }//GEN-LAST:event_BuildingLabel9MouseClicked

    private void BuildingLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuildingLabel10MouseClicked
    	setObjectBuy(10);
    }//GEN-LAST:event_BuildingLabel10MouseClicked

    private void BuildingLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuildingLabel11MouseClicked
    	setObjectBuy(11);
    }//GEN-LAST:event_BuildingLabel11MouseClicked

    private void BuildingLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuildingLabel12MouseClicked
    	setObjectBuy(12);
    }//GEN-LAST:event_BuildingLabel12MouseClicked

    private void BuildingLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuildingLabel13MouseClicked
    	setObjectBuy(13);
    }//GEN-LAST:event_BuildingLabel13MouseClicked

    private void BuildingLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuildingLabel14MouseClicked
    	setObjectBuy(14);
    }//GEN-LAST:event_BuildingLabel14MouseClicked

    private void BuildingLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuildingLabel15MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BuildingLabel15MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BuildingLabel0;
    private javax.swing.JLabel BuildingLabel1;
    private javax.swing.JLabel BuildingLabel10;
    private javax.swing.JLabel BuildingLabel11;
    private javax.swing.JLabel BuildingLabel12;
    private javax.swing.JLabel BuildingLabel13;
    private javax.swing.JLabel BuildingLabel14;
    private javax.swing.JLabel BuildingLabel15;
    private javax.swing.JLabel BuildingLabel2;
    private javax.swing.JLabel BuildingLabel3;
    private javax.swing.JLabel BuildingLabel4;
    private javax.swing.JLabel BuildingLabel5;
    private javax.swing.JLabel BuildingLabel6;
    private javax.swing.JLabel BuildingLabel7;
    private javax.swing.JLabel BuildingLabel8;
    private javax.swing.JLabel BuildingLabel9;
    private javax.swing.JLabel CostLabel;
    private javax.swing.JLabel SelectionLabel;
    // End of variables declaration//GEN-END:variables
}
