/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package agesgame;

import java.awt.event.KeyEvent;

/**
 *
 * @author cpemm_000
 */
public class MainImpl extends javax.swing.JPanel {

    private GameDataClass game;
    private CityViewImpl cityView;
    private TitleImpl titleScreen;
    private float SCALE;
            
    public MainImpl(GameDataClass game, GameTablesClass tables, float SCALE, String version) {
        this.game = game;
        this.SCALE = SCALE;
        initComponents();
        
    }
    public void openTitle(String ver){
    	titleScreen =  new TitleImpl(this,ver);
    	this.add(titleScreen);
    	titleScreen.setSize(this.getSize());
    }
    public void setCityView(boolean debug){
        System.out.println("Set City View");
        game.setupNewGame(debug);
        cityView = new CityViewImpl(game, SCALE);
        
        TimerClass screenTimer = new TimerClass(this,200);
        this.add(cityView);
        cityView.setSize(this.getSize());
    }

    void startNew(boolean debug){
    	this.remove(titleScreen);
        setCityView(debug);
    } 
    
    public void timerTick(){
        cityView.timeTick();
    }

    public void keyPressed(KeyEvent event) {
        System.out.println("MainImpl - Key: " + event.getKeyChar());
    }
    public int getScaledValue(int in){
    	return Math.round(in * SCALE);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, getScaledValue(1600), Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, getScaledValue(800), Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        keyPressed(evt);
    }//GEN-LAST:event_formKeyPressed

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
        keyPressed(evt);
    }//GEN-LAST:event_formKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
