package agesgame;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JTextField;

public class ResourceImpl extends javax.swing.JPanel {
    private GameDataClass game;
    private CityViewImpl upperView;
            
    public ResourceImpl(GameDataClass game,CityViewImpl cityView) {
        this.game = game;
        upperView = cityView;
        initComponents();
        scaleView();
        generateDisplay();
    }
    public void generateDisplay(){

        for (int i = 0; i < 10; i++){
            getResourceIcon(i).setIcon(new ImageIcon(game.tables.getResourceIcon(i).getScaledInstance(upperView.Scale(25), upperView.Scale(25), 0) ) );
            getResourceIcon(i).setText("");
            getReourceCountLabel(i).setText(game.getResource(i)+"");
        }
    }
    public void close(){
        this.hide();
    }

    public JLabel getReourceCountLabel(int i) {
        if (i == 0) {
            return JobLabel0;
        }if (i == 1) {
            return JobLabel1;
        }if (i == 2) {
            return JobLabel2;
        }if (i == 3) {
            return JobLabel3;
        }if (i == 4) {
            return JobLabel4;
        }if (i == 5) {
            return JobLabel5;
        }if (i == 6) {
            return JobLabel6;
        }if (i == 7) {
            return JobLabel7;
        }if (i == 8) {
            return JobLabel8;
        }if (i == 9) {
            return JobLabel9;
        }
        return null;
    }
    public JLabel getResourceIcon(int i){
        if (i == 0) {
            return ResLabel0;
        }if (i == 1) {
            return ResLabel1;
        }if (i == 2) {
            return ResLabel2;
        }if (i == 3) {
            return ResLabel3;
        }if (i == 4) {
            return ResLabel4;
        }if (i == 5) {
            return ResLabel5;
        }if (i == 6) {
            return ResLabel6;
        }if (i == 7) {
            return ResLabel7;
        }if (i == 8) {
            return ResLabel8;
        }if (i == 9) {
            return ResLabel9;
        }
        return null;
    }

    public void scaleView(){
    	CloseLabel.setBounds(upperView.Scale(CloseLabel.getX()), upperView.Scale(CloseLabel.getY()), upperView.Scale(CloseLabel.getWidth()), upperView.Scale(CloseLabel.getHeight()));
    	CloseLabel.setFont(new java.awt.Font("Tahoma", 1, upperView.Scale(14))); // NOI18N
    	
    	ItemsLabel.setBounds(upperView.Scale(ItemsLabel.getX()), upperView.Scale(ItemsLabel.getY()), upperView.Scale(ItemsLabel.getWidth()), upperView.Scale(ItemsLabel.getHeight()));
    	
    	for (int i = 0; i < 10; i ++){
    		getReourceCountLabel(i).setBounds(upperView.Scale(getReourceCountLabel(i).getX()), upperView.Scale(getReourceCountLabel(i).getY()), upperView.Scale(getReourceCountLabel(i).getWidth()), upperView.Scale(getReourceCountLabel(i).getHeight()));
    		getReourceCountLabel(i).setFont(new java.awt.Font("Tahoma", 1, upperView.Scale(14))); // NOI18N
    		
    		getResourceIcon(i).setBounds(upperView.Scale(getResourceIcon(i).getX()), upperView.Scale(getResourceIcon(i).getY()), upperView.Scale(25),upperView.Scale(25));
        	
        }
    	jPanel1.setBounds(upperView.Scale(jPanel1.getX()), upperView.Scale(jPanel1.getY()), upperView.Scale(jPanel1.getWidth()), upperView.Scale(jPanel1.getHeight()));

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CloseLabel = new javax.swing.JLabel();
        JobLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        ResLabel0 = new javax.swing.JLabel();
        JobLabel0 = new javax.swing.JLabel();
        ResLabel1 = new javax.swing.JLabel();
        JobLabel1 = new javax.swing.JLabel();
        ResLabel2 = new javax.swing.JLabel();
        JobLabel2 = new javax.swing.JLabel();
        ResLabel3 = new javax.swing.JLabel();
        JobLabel3 = new javax.swing.JLabel();
        ResLabel4 = new javax.swing.JLabel();
        JobLabel4 = new javax.swing.JLabel();
        ResLabel5 = new javax.swing.JLabel();
        ResLabel6 = new javax.swing.JLabel();
        JobLabel5 = new javax.swing.JLabel();
        JobLabel6 = new javax.swing.JLabel();
        JobLabel8 = new javax.swing.JLabel();
        ResLabel7 = new javax.swing.JLabel();
        ResLabel8 = new javax.swing.JLabel();
        JobLabel9 = new javax.swing.JLabel();
        ResLabel9 = new javax.swing.JLabel();
        ItemsLabel = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setLayout(null);

        CloseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        CloseLabel.setText("X");
        CloseLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseLabelMouseClicked(evt);
            }
        });
        add(CloseLabel);
        CloseLabel.setBounds(560, 0, 12, 14);

        JobLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JobLabel7.setText("000");
        add(JobLabel7);
        JobLabel7.setBounds(70, 40, 26, 17);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        ResLabel0.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ResLabel0.setText("R0");
        jPanel1.add(ResLabel0);
        ResLabel0.setBounds(20, 20, 40, 17);

        JobLabel0.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JobLabel0.setText("000");
        jPanel1.add(JobLabel0);
        JobLabel0.setBounds(60, 20, 26, 17);

        ResLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ResLabel1.setText("R1");
        jPanel1.add(ResLabel1);
        ResLabel1.setBounds(20, 50, 40, 17);

        JobLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JobLabel1.setText("000");
        jPanel1.add(JobLabel1);
        JobLabel1.setBounds(60, 50, 26, 17);

        ResLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ResLabel2.setText("R2");
        jPanel1.add(ResLabel2);
        ResLabel2.setBounds(20, 80, 40, 17);

        JobLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JobLabel2.setText("000");
        jPanel1.add(JobLabel2);
        JobLabel2.setBounds(60, 80, 26, 17);

        ResLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ResLabel3.setText("R3");
        jPanel1.add(ResLabel3);
        ResLabel3.setBounds(20, 110, 40, 17);

        JobLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JobLabel3.setText("000");
        jPanel1.add(JobLabel3);
        JobLabel3.setBounds(60, 110, 26, 17);

        ResLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ResLabel4.setText("R3");
        jPanel1.add(ResLabel4);
        ResLabel4.setBounds(130, 20, 40, 17);

        JobLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JobLabel4.setText("000");
        jPanel1.add(JobLabel4);
        JobLabel4.setBounds(170, 20, 26, 17);

        ResLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ResLabel5.setText("R5");
        jPanel1.add(ResLabel5);
        ResLabel5.setBounds(130, 50, 40, 17);

        ResLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ResLabel6.setText("R6");
        jPanel1.add(ResLabel6);
        ResLabel6.setBounds(130, 80, 40, 17);

        JobLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JobLabel5.setText("000");
        jPanel1.add(JobLabel5);
        JobLabel5.setBounds(170, 50, 26, 17);

        JobLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JobLabel6.setText("000");
        jPanel1.add(JobLabel6);
        JobLabel6.setBounds(170, 80, 26, 17);

        add(jPanel1);
        jPanel1.setBounds(10, 250, 230, 140);

        JobLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JobLabel8.setText("000");
        add(JobLabel8);
        JobLabel8.setBounds(150, 40, 26, 17);

        ResLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ResLabel7.setText("R2");
        add(ResLabel7);
        ResLabel7.setBounds(30, 40, 40, 17);

        ResLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ResLabel8.setText("R2");
        add(ResLabel8);
        ResLabel8.setBounds(110, 40, 40, 17);

        JobLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JobLabel9.setText("000");
        add(JobLabel9);
        JobLabel9.setBounds(240, 40, 26, 17);

        ResLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ResLabel9.setText("R2");
        add(ResLabel9);
        ResLabel9.setBounds(200, 40, 40, 17);

        ItemsLabel.setBackground(new java.awt.Color(255, 0, 255));
        ItemsLabel.setText("ITEMS");
        ItemsLabel.setOpaque(true);
        ItemsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ItemsLabelMouseClicked(evt);
            }
        });
        add(ItemsLabel);
        ItemsLabel.setBounds(450, 330, 60, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void CloseLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseLabelMouseClicked
        close();
    }//GEN-LAST:event_CloseLabelMouseClicked

    private void ItemsLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ItemsLabelMouseClicked
        upperView.showItemsScreen();
    }//GEN-LAST:event_ItemsLabelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CloseLabel;
    private javax.swing.JLabel ItemsLabel;
    private javax.swing.JLabel JobLabel0;
    private javax.swing.JLabel JobLabel1;
    private javax.swing.JLabel JobLabel2;
    private javax.swing.JLabel JobLabel3;
    private javax.swing.JLabel JobLabel4;
    private javax.swing.JLabel JobLabel5;
    private javax.swing.JLabel JobLabel6;
    private javax.swing.JLabel JobLabel7;
    private javax.swing.JLabel JobLabel8;
    private javax.swing.JLabel JobLabel9;
    private javax.swing.JLabel ResLabel0;
    private javax.swing.JLabel ResLabel1;
    private javax.swing.JLabel ResLabel2;
    private javax.swing.JLabel ResLabel3;
    private javax.swing.JLabel ResLabel4;
    private javax.swing.JLabel ResLabel5;
    private javax.swing.JLabel ResLabel6;
    private javax.swing.JLabel ResLabel7;
    private javax.swing.JLabel ResLabel8;
    private javax.swing.JLabel ResLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
